<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @escapeNotVerified */ echo $block->getMiscellaneousHtml();?>
<div class="footer-container-bottom">
	<div class="footer-bottom-content">
		<address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
				
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_social_bottom')->toHtml();?>
	</div>
</div>
